on:
  push:
    branches:
      - main

name: Package

jobs:
  check:
    name: Package distribution file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Package
        run: |
          npm ci
          npm run build
          npm run package
      - name: Commit
        run: |
          git config --global user.name "GitHub Actions"
          git add dist/
          git commit -m "(chore) updating dist" || echo "No changes to commit"
          git push origin HEAD:main
      - name: Check for tag
        run: |
          current_version=$(npm run version --loglevel silent)
          echo "release_version=$current_version" >> $GITHUB_ENV
          if [ $(git tag -l "v$version") ]; then
              echo "skip_release=true" >> $GITHUB_ENV
          fi
      - name: Create Release
        if: ${{ env.skip_release != 'true' }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ env.release_version }}"
          release_name: Release ${{ env.release_version }}
          body: |
            TBD
          draft: false
          prerelease: false